stages:
  create_general_processed_data:
    cmd: python scripts/rebuild_processed_data.py
    deps:
      - src/preprocess/preprocess_general.py
      - data/raw/results.csv
      - data/raw/qualifying.csv
      - data/raw/drivers.csv
      - data/raw/constructors.csv
      - data/raw/circuits.csv
      - data/raw/status.csv
      - data/raw/lap_times.csv
    outs:
      - data/processed/race_weather.csv
      - data/processed/countries.csv
      - data/processed/circuits.csv
      - data/processed/constructors.csv
      - data/processed/drivers.csv
      - data/processed/races.csv

  create_mainrace_training_data:
    cmd: python scripts/create_mainrace_training.py
    deps:
      - src/preprocess/preprocess_mainrace.py
      - src/preprocess/preprocess_general.py
      - data/processed/countries.csv
      - data/processed/races.csv
      - data/raw/results.csv
      - data/raw/qualifying.csv
      - data/raw/drivers.csv
      - data/raw/constructors.csv
      - data/raw/circuits.csv
      - data/raw/status.csv
      - data/raw/lap_times.csv
    outs:
      - data/processed/cleaned_data_main_race_with_median.csv

  create_qualifying_training_data:
    cmd: python scripts/create_qualifying_training.py
    deps:
      - src/preprocess/preprocess_qualifying.py
      - src/preprocess/preprocess_general.py
      - data/processed/countries.csv
      - data/processed/races.csv
      - data/raw/results.csv
      - data/raw/qualifying.csv
      - data/raw/drivers.csv
      - data/raw/constructors.csv
      - data/raw/circuits.csv
      - data/raw/status.csv
      - data/raw/lap_times.csv
    outs:
      - data/processed/cleaned_data_qualifying_with_median.csv

  create_status_training_data:
    cmd: python scripts/create_status_training.py
    deps:
      - src/preprocess/preprocess_status.py
      - src/preprocess/preprocess_general.py
      - data/processed/countries.csv
      - data/processed/races.csv
      - data/raw/results.csv
      - data/raw/qualifying.csv
      - data/raw/drivers.csv
      - data/raw/constructors.csv
      - data/raw/circuits.csv
      - data/raw/status.csv
      - data/raw/lap_times.csv
    outs:
      - data/processed/cleaned_data_status.csv

  train_mainrace_model:
    cmd: python scripts/train_mainrace_model.py
    deps:
      - scripts/train_mainrace_model.py
      - src/models/mainrace_pipeline.py
      - data/processed/cleaned_data_main_race_with_median.csv
    outs:
      - models/trained_mainrace_pipeline.pkl

  train_qualifying_model:
    cmd: python scripts/train_qualifying_model.py
    deps:
      - scripts/train_qualifying_model.py
      - src/models/qualifying_pipeline.py
      - data/processed/cleaned_data_qualifying_with_median.csv
    outs:
      - models/trained_qualifying_pipeline.pkl

  train_status_model:
    cmd: python scripts/train_status_model.py
    deps:
      - scripts/train_status_model.py
      - src/models/status_pipeline.py
      - data/processed/cleaned_data_status.csv
    outs:
      - models/trained_status_pipeline.pkl