name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: sudo apt-get update -y && sudo apt-get install -y build-essential curl

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Sync dependencies
        run: uv sync

      - name: Configure GCP credentials
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: echo "$GCP_SA_KEY" > gcloud-key.json

      - name: Modify DVC remote
        run: uv run dvc remote modify --local myremote credentialpath gcloud-key.json

      - name: Pull data with DVC
        run: uv run dvc pull

      - name: Run tests
        run: uv run pytest -q