name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system deps
        run: sudo apt-get update -y && sudo apt-get install -y build-essential

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install "dvc[gs]" gcsfs

      - name: Configure GCP credentials
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "GCP_SA_KEY " > /tmp/gcloud-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcloud-key.json
          # optional verify: gsutil ls gs://your-bucket || true

      - name: DVC pull artifacts
        run: dvc pull

      - name: Run tests
        run: pytest -q